name: Test Note-Taker App (Conda)

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.10
          environment-file: environment.yml
          activate-environment: note-taker

      - name: Verify environment
        run: |
          conda info
          conda list

      - name: Lint with flake8
        run: |
          flake8 note_taker/ tests/

      - name: Run tests
        run: |
          pytest -v
